# Generated by Django 3.0.3 on 2020-12-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201027_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GRAINS', 'Grains & Pulses'), ('SNACKS', 'Snacks'), ('BREAKFAST', 'Breakfast'), ('VEG', 'Fruit&Veg'), ('DAIRY', 'Dairy')], default='', max_length=20),
        ),
    ]
